#scrolling= "natural"
[theme] 
name= "space-villain"

[theme.overrides]
separator=" "

[icons]
name= "awesome"

[[block]]
block="focused_window"
max_width = 80
show_marks = "all"

[[block]]
block = "music"
buttons = ["prev", "play", "next"]
dynamic_width = true
#marquee_interval= 2
#marquee_speed= 0.5

[[block]]
block = "net"
format = "{ip}{speed_down;K*B}{speed_up;K*B}"
interval = 5
[block.theme_overrides]
idle_bg = "#000219"

#[[block]]
#block = "disk_space"
#path = "/"
#info_type = "available"
#unit = "GB"
#interval = 60
#warning = 20.0
#alert = 10.0
#format = "{icon} {available}"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used}"
format_swap = "{swap_used_percents}"
#[block.theme_overrides]
#idle_bg = "#002420"

[[block]]
block = "cpu"
interval = 5
format = "{utilization} {frequency}"
#034521
#[[block]]
#block = "load"
#interval = 1
#format = "{1m}"


[[block]]
block = "sound"
step_width = 2
format = "{volume}"
on_click = "/usr/bin/pavucontrol"
[block.theme_overrides]
idle_bg = "#1D0000"

[[block]]
block = "battery"
interval = 10
format = "{percentage} {time}"
[block.theme_overrides]
good_bg = "#002420"

[[block]]
block = "backlight"
device= "acpi_video0"

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{average}"
chip = "coretemp-isa-0000"
#inputs = ["CPUTIN", "SYSTIN"]

[[block]]
block = "time"
interval = 60
format = "%d/%m/%y | %a %I:%M %p"

#[[block]]
#block = "notify"

